sudo: required

language: c++

services:
  - docker
  
before_install:
  - docker pull graemeastewart/u16-dev
 
install:
  - /bin/true

script:
  - docker run -v $(pwd):/mnt graemeastewart/u16-dev /mnt/.travis-scripts/build-test.sh
