sudo: required

# Add only master and stable branches
branches:
  only:
    - master
    - stable

# Notify on failure
notifications:
  email: on_failure

# Test across multiple containers
env:
  - DIMAGE=hepsoftwarefoundation/c7-dev  CMAKE=cmake3
  - DIMAGE=hepsoftwarefoundation/c7-dev  CMAKE=cmake3 CMAKE_EXTRA=-DPYTHON_TEST=python2
  - DIMAGE=hepsoftwarefoundation/u18-dev CMAKE_EXTRA=-Dnlohmann_json_DIR=/usr/lib/cmake
  - DIMAGE=hepsoftwarefoundation/c8-dev
  - DIMAGE=hepsoftwarefoundation/u20-dev CXX=g++-9 CC=gcc-9

services:
  - docker

before_install:
  - docker pull $DIMAGE

install:
  - /bin/true

# Light customisation of build for different container images
script:
  - if [ "$DIMAGE" = hepsoftwarefoundation/c7-dev ];  then docker run -v $(pwd):/mnt $DIMAGE scl enable devtoolset-8 /mnt/.travis-scripts/build-test.sh; fi
  - if [ "$DIMAGE" = hepsoftwarefoundation/u18-dev ]; then docker run -v $(pwd):/mnt $DIMAGE /mnt/.travis-scripts/build-test.sh; fi
  - if [ "$DIMAGE" = hepsoftwarefoundation/c8-dev ];  then docker run -v $(pwd):/mnt $DIMAGE /mnt/.travis-scripts/build-test.sh; fi
  - if [ "$DIMAGE" = hepsoftwarefoundation/u20-dev ]; then docker run -v $(pwd):/mnt $DIMAGE /mnt/.travis-scripts/build-test.sh; fi
