# Name of the workflow
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master and stable branches
on:
  push:
    branches: [ master, stable ]
  pull_request:
    branches: [ master, stable ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Main building and testing
  build-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Define the platforms to run on. Later determines the Docker image that'll be used
    strategy:
      matrix:
        platform: [ c7-dev_py2, c7-dev, c8-dev, u18-dev, u20-dev ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out our repository under $GITHUB_WORKSPACE, so our job can access it
    - uses: actions/checkout@v2

    # Sets up useful environment variables
    - name: Setup environment variables
      run: |
        echo "::set-env name=DIMAGE::hepsoftwarefoundation/${PLATFORM/_py2/}"
        if [[ "$PLATFORM" == *_py2 ]];
        then
          echo "::set-env name=CMAKE_EXTRA::-DPYTHON_TEST=python2"
        fi
      env:
        PLATFORM: ${{ matrix.platform }}

    # Pulls the associated Docker image
    - name: Docker pull
      run: docker pull $DIMAGE

    # Builds the code and runs the test
    - name: Build and test
      run: |
        if [[ "$DIMAGE" == *c7-dev ]];
        then
          docker run -e CMAKE=cmake3 -e CMAKE_EXTRA=$CMAKE_EXTRA -v $(pwd):/mnt $DIMAGE scl enable devtoolset-8 /mnt/.github/scripts/build-test.sh;
        elif [[ "$DIMAGE" == *c8-dev ]];
        then
          docker run -v $(pwd):/mnt $DIMAGE /mnt/.github/scripts/build-test.sh;
        elif [[ "$DIMAGE" == *u18-dev ]];
        then
          docker run -e CMAKE_EXTRA=-Dnlohmann_json_DIR=/usr/lib/cmake -v $(pwd):/mnt $DIMAGE /mnt/.github/scripts/build-test.sh;
        elif [[ "$DIMAGE" == *u20-dev ]];
        then
          docker run -e CXX=g++-9 -e CC=gcc-9 -v $(pwd):/mnt $DIMAGE /mnt/.github/scripts/build-test.sh;
        else
          echo "Unkown Docker Image: $DIMAGE"
        fi
