# Name of the workflow
name: Clang-Format

# Controls when the action will run. Triggers the workflow on push for all branches
on: push

# Defines the main job where we checkout our code, run clang-format and commit changes
jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: amete/clang-format-action@v0.1
